n1=input("Hiii! Lets play a fooody madlib!!\n Enter an adjective ")
n2=input(" Now a nationality(eg: Indian etc) ")
n3=input(" Be creative and tell me a persons name ")
n4=input(" Now a noun ")
n5=input(" Time for an adjective ")
n6=input(" Need a noun again :) ")
n7=input(" Adjective time ")
n8=input(" One more adjective ")
n9=input(" This time input a plural noun ")
n10=input(" Now another noun ")
n11=input(" Give a number ")
n12=input(" Input a shape ")
n13=input(" Now a food ")
n14=input(" Another food ")
n15=input(" Last another number needed ")
print("Let's see what you made !!\n")

print("Pizza was invented by a "+ n1 +" "+ n2+" chef named "+n3+". To make a pizza, you need to take a lump of "+n4+ ", and make a thin, round "+n5+" "+n6+". Then you cover it with "+n7+" sauce,"+n8+" cheese, and fresh chopped "+n9+". Next you have to bake it in a very hot "+n10+". When it is done,cut it into "+n11+" "+n12+". Some kids like "+n13+" pizza the best, but my favorite is the "+n14+" pizza. If I could, I would eat pizza "+n15+" times a day!")

print("\n Hope you had fun reading :)!!")